### ISSUE TITLE
doublepress came together with press

### ISSUE THREAD

**Issue by marcellgeng** [ruiseixasm/Versatile_RotaryEncoder#6]
Hello,

I don't know where I made a mistake, but in the sample, the double press came with the press answer too:
20:15:45.577 -> #4.1 Pressed
20:15:47.714 -> #4.1 Pressed
20:15:47.901 -> #4.2 Double Pressed

I thought it should be a different answer for different actions. 
Am I wrong?
Sorry for the silly question. I'm a newbie.

Thanks for your feedback.

**Comment by ruiseixasm** [comment]
Your results are correct, 47.901 - 47.714 < 250ms, thus activating the Double Press, while 47.714 - 45.577 > 250ms, the default value for `DoublePressDuration`. For different `DoublePressDuration` values check the following method:
```
Versatile_RotaryEncoder.setDoublePressDuration( unsigned int duration )
By default it's set up to 250 ms for repeated presses be considered a double press, you can set a different value with this function.
```

**Comment by marcellgeng** [comment]
I totally understand this part. I'm just wondering why appears 2 single clicks before the double-click. 

The _void handlePress() {....}_; runs twice **before** the void _handleDoublePress() {...}._
It would be beneficial to me,  if just the _void handleDoublePress() {..._} would run **instead** of the two loop of _void handlePress() {....};._

I'm not sure if I could explain it well.

**Comment by ruiseixasm** [comment]
Ok, I got you. The double press works just like the Windows double click, it doesn't work **instead of** the single click, the single click also happens, that's why you shouldn't use it together with toggling operations on that single click but just selecting ones, exactly like on windows. However, if you need an **instead of** operation in order to avoid say, double toggling, you should use long press instead toghether with press release. This way you do `setHandlePressRelease` for one operation and `setHandleLongPress` for the complementary other, knowing that they will become mutually exclusive, **instead of**.
Regardless, the double press works just like your computer mouse double click, it also triggers the first single click, and thus that single press should never be associated with a toggling function.
